from selenium import webdriver
import time 

driver = webdriver.Chrome('/Users/임재원/Downloads/chromedriver')
driver.implicitly_wait(5)
driver.get('https://naver.com')
driver.implicitly_wait(2)

while True:
	driver.find_element_by_name('query').send_keys('자라킹')
	time.sleep(5)
	driver.find_element_by_id('search_btn').click()
	time.sleep(5)
	driver.find_element_by_class_name('go_more').click()
	time.sleep(5)
	driver.find_element_by_link_text('자라나는 자신감! 자라킹').click()
	time.sleep(5)
	driver.get('https://naver.com')
	time.sleep(5)
	driver.switch_to_window(driver.window_handles[1]) 
	driver.get_window_position(driver.window_handles[1])
	time.sleep(5)
	driver.close()
	time.sleep(5)
	driver.switch_to_window(driver.window_handles[0]) 
	driver.get_window_position(driver.window_handles[0])
	time.sleep(3)
	driver.delete_all_cookies()
	time.sleep(3)
	driver.get('chrome://settings/clearBrowserData')
	time.sleep(2)
	driver.find_elements_by_partial_link_text('인터넷 사용 기록 삭제').click()
	time.sleep(2)
	driver.get('https://naver.com')
	time.sleep(2)